# Generated by Django 3.1 on 2020-11-20 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('longitude', models.IntegerField(default=0)),
                ('lattitude', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=256)),
                ('hospital_longitude', models.IntegerField(default=0)),
                ('hospital_lattitude', models.IntegerField(default=0)),
                ('phone_no', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Scooty', 'Scooty')], default='Car', max_length=100)),
                ('number', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('to_family', 'Family'), ('to_hospital', 'Hospital')], default='to_family', max_length=256)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Accidents.accident')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='AccidentImages')),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Accidents.accident')),
            ],
        ),
        migrations.AddField(
            model_name='accident',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='Accidents.hospital'),
        ),
        migrations.AddField(
            model_name='accident',
            name='vehicles',
            field=models.ManyToManyField(to='Accidents.Vehicle'),
        ),
    ]
