# Generated by Django 3.0.11 on 2020-11-21 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accidents', '0002_auto_20201121_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='Accidents.Hospital'),
        ),
    ]
