# Generated by Django 3.0.11 on 2020-11-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accidents', '0003_auto_20201121_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_latitude',
            new_name='hospital_lattitude',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Scooty', 'Scooty')], default='Car', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='AccidentImages'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
